### ISSUE TITLE
Calculation runs indefinitely in a special case

### ISSUE THREAD

**Issue by daniel-lerch** [juliuste/sainte-lague#3]
### Description ###
The Saint-Laguë method does work in all cases when different parties have the same number of votes. In Germany the disputed seat is randomly given to one of the parties with the same count of votes.

This case is very unlikely in a real parliamentary election but gets more likely when the count of votes in total decreases. And you can perfectly use Saint-Laguë for different cases than parliamentary elections. I have ported your code to C# and use it for a Vocabulary trainer where it causes problems: daniel-lerch/vocup#11.

### How to reproduce ###
Your implementation does not handle the case of same vote counts in any way. If you have three parties, each with four votes and you want to distribute two seats, your method will run indefinitely and never find a result.

I would suppose to either implement a random distribution between parties with the same count of votes or to throw an exception.

**Comment by juliuste** [comment]
Thank you very much for reporting this! I must have somehow overlooked this issue in December and only discovered it now, sorry about that 🙈! [`c971069`](https://github.com/juliuste/sainte-lague/commit/c9710698ced64b5585afa64765dc9a7605a6d3ae) should fix the issue.
